package output

import (
	"fmt"
	"io"
	"mime"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"time"
)

// FileStreamOutput represents a response that serves a file inline (for viewing in browser)
// Similar to Laravel's response()->file()
type FileStreamOutput struct {
	filePath    string
	fileName    string
	content     []byte
	code        int
	headers     map[string]string
	contentType string
	isInline    bool
	eTag        string
	lastMod     time.Time
	cacheMaxAge int // seconds, 0 = no cache
}

// FileOutputOption configures a FileStreamOutput
type FileOutputOption func(*FileStreamOutput)

// WithFileHeaders adds custom headers
func WithFileHeaders(headers map[string]string) FileOutputOption {
	return func(f *FileStreamOutput) {
		for k, v := range headers {
			f.headers[k] = v
		}
	}
}

// WithFileContentType overrides auto-detected content type
func WithFileContentType(contentType string) FileOutputOption {
	return func(f *FileStreamOutput) {
		f.contentType = contentType
	}
}

// WithCache sets cache headers (max-age in seconds)
func WithCache(maxAge int) FileOutputOption {
	return func(f *FileStreamOutput) {
		f.cacheMaxAge = maxAge
	}
}

// WithETag sets a custom ETag
func WithETag(eTag string) FileOutputOption {
	return func(f *FileStreamOutput) {
		f.eTag = eTag
	}
}

// WithLastModified sets the Last-Modified header
func WithLastModified(t time.Time) FileOutputOption {
	return func(f *FileStreamOutput) {
		f.lastMod = t
	}
}

// WithFileName sets a custom display name
func WithFileName(name string) FileOutputOption {
	return func(f *FileStreamOutput) {
		f.fileName = name
	}
}

// File serves a file for inline viewing (e.g., images, PDFs in browser)
// Similar to Laravel's response()->file()
func File(path string, opts ...FileOutputOption) *FileStreamOutput {
	contentType := detectMimeType(path)
	fileName := filepath.Base(path)

	f := &FileStreamOutput{
		filePath:    path,
		fileName:    fileName,
		content:     nil,
		code:        http.StatusOK,
		headers:     make(map[string]string),
		contentType: contentType,
		isInline:    true,
		cacheMaxAge: 0,
	}

	for _, opt := range opts {
		opt(f)
	}

	return f
}

// FileFromContent serves content as a file for inline viewing
func FileFromContent(content []byte, filename string, opts ...FileOutputOption) *FileStreamOutput {
	contentType := detectMimeTypeFromFilename(filename)

	f := &FileStreamOutput{
		filePath:    "",
		fileName:    filename,
		content:     content,
		code:        http.StatusOK,
		headers:     make(map[string]string),
		contentType: contentType,
		isInline:    true,
		cacheMaxAge: 0,
	}

	for _, opt := range opts {
		opt(f)
	}

	return f
}

// Download serves a file as a downloadable attachment
// Similar to Laravel's response()->download()
func Download(path string, opts ...FileOutputOption) *FileStreamOutput {
	contentType := detectMimeType(path)
	fileName := filepath.Base(path)

	f := &FileStreamOutput{
		filePath:    path,
		fileName:    fileName,
		content:     nil,
		code:        http.StatusOK,
		headers:     make(map[string]string),
		contentType: contentType,
		isInline:    false,
		cacheMaxAge: 0,
	}

	for _, opt := range opts {
		opt(f)
	}

	return f
}

// DownloadWithName serves a file with a custom download name
// Similar to Laravel's response()->download($path, $name)
func DownloadWithName(path string, downloadName string, opts ...FileOutputOption) *FileStreamOutput {
	contentType := detectMimeType(path)

	f := &FileStreamOutput{
		filePath:    path,
		fileName:    downloadName,
		content:     nil,
		code:        http.StatusOK,
		headers:     make(map[string]string),
		contentType: contentType,
		isInline:    false,
		cacheMaxAge: 0,
	}

	for _, opt := range opts {
		opt(f)
	}

	return f
}

// DownloadFromContent serves content as a downloadable file
func DownloadFromContent(content []byte, filename string, opts ...FileOutputOption) *FileStreamOutput {
	contentType := detectMimeTypeFromFilename(filename)

	f := &FileStreamOutput{
		filePath:    "",
		fileName:    filename,
		content:     content,
		code:        http.StatusOK,
		headers:     make(map[string]string),
		contentType: contentType,
		isInline:    false,
		cacheMaxAge: 0,
	}

	for _, opt := range opts {
		opt(f)
	}

	return f
}

// StreamDownload creates a download from a streaming callback
// Similar to Laravel's response()->streamDownload()
type StreamDownloadOutput struct {
	fileName    string
	callback    func(writer func([]byte) error) error
	code        int
	headers     map[string]string
	contentType string
}

// StreamDownload serves content generated by a callback as a download
// Useful for generating large files on-the-fly (e.g., CSV exports)
func StreamDownload(filename string, callback func(writer func([]byte) error) error, opts ...FileOutputOption) *StreamDownloadOutput {
	contentType := detectMimeTypeFromFilename(filename)

	s := &StreamDownloadOutput{
		fileName:    filename,
		callback:    callback,
		code:        http.StatusOK,
		headers:     make(map[string]string),
		contentType: contentType,
	}

	// Apply opts that are compatible
	tempFile := &FileStreamOutput{headers: s.headers, contentType: s.contentType}
	for _, opt := range opts {
		opt(tempFile)
	}
	s.headers = tempFile.headers
	s.contentType = tempFile.contentType

	return s
}

// Data returns nil as streaming is handled separately
func (s *StreamDownloadOutput) Data() any {
	return nil
}

// Code returns the HTTP status code
func (s *StreamDownloadOutput) Code() int {
	return s.code
}

// Headers returns the headers including Content-Disposition
func (s *StreamDownloadOutput) Headers() map[string]string {
	headers := make(map[string]string)
	for k, v := range s.headers {
		headers[k] = v
	}
	headers["Content-Disposition"] = fmt.Sprintf(`attachment; filename="%s"`, s.fileName)
	headers["Content-Type"] = s.contentType
	return headers
}

// ContentType returns the content type
func (s *StreamDownloadOutput) ContentType() string {
	return s.contentType
}

// StreamCallback returns the streaming callback
func (s *StreamDownloadOutput) StreamCallback() func(writer func([]byte) error) error {
	return s.callback
}

// FilePath returns empty (not a file-based output)
func (s *StreamDownloadOutput) FilePath() string {
	return ""
}

// FileName returns the download filename
func (s *StreamDownloadOutput) FileName() string {
	return s.fileName
}

// IsInline returns false (always a download)
func (s *StreamDownloadOutput) IsInline() bool {
	return false
}

// Data returns the file content or reads from path
func (f *FileStreamOutput) Data() any {
	if f.content != nil {
		return f.content
	}

	// Read file content
	file, err := os.Open(f.filePath)
	if err != nil {
		return []byte(fmt.Sprintf("Error opening file: %v", err))
	}
	defer file.Close()

	content, err := io.ReadAll(file)
	if err != nil {
		return []byte(fmt.Sprintf("Error reading file: %v", err))
	}

	return content
}

// Code returns the HTTP status code
func (f *FileStreamOutput) Code() int {
	return f.code
}

// Headers returns all headers including Content-Disposition
func (f *FileStreamOutput) Headers() map[string]string {
	headers := make(map[string]string)
	for k, v := range f.headers {
		headers[k] = v
	}

	// Set Content-Disposition
	if f.isInline {
		headers["Content-Disposition"] = fmt.Sprintf(`inline; filename="%s"`, f.fileName)
	} else {
		headers["Content-Disposition"] = fmt.Sprintf(`attachment; filename="%s"`, f.fileName)
	}

	// Set Content-Type
	headers["Content-Type"] = f.contentType

	// Set Content-Length if we have content
	if f.content != nil {
		headers["Content-Length"] = strconv.Itoa(len(f.content))
	} else if f.filePath != "" {
		if info, err := os.Stat(f.filePath); err == nil {
			headers["Content-Length"] = strconv.FormatInt(info.Size(), 10)
		}
	}

	// Set cache headers
	if f.cacheMaxAge > 0 {
		headers["Cache-Control"] = fmt.Sprintf("public, max-age=%d", f.cacheMaxAge)
	} else {
		headers["Cache-Control"] = "no-cache, no-store, must-revalidate"
		headers["Pragma"] = "no-cache"
		headers["Expires"] = "0"
	}

	// Set ETag if provided
	if f.eTag != "" {
		headers["ETag"] = f.eTag
	}

	// Set Last-Modified if provided
	if !f.lastMod.IsZero() {
		headers["Last-Modified"] = f.lastMod.UTC().Format(http.TimeFormat)
	}

	return headers
}

// ContentType returns the MIME type
func (f *FileStreamOutput) ContentType() string {
	return f.contentType
}

// FilePath returns the file path
func (f *FileStreamOutput) FilePath() string {
	return f.filePath
}

// FileName returns the display filename
func (f *FileStreamOutput) FileName() string {
	return f.fileName
}

// IsInline returns true if file should be displayed inline
func (f *FileStreamOutput) IsInline() bool {
	return f.isInline
}

// SetFileName changes the download/display filename
func (f *FileStreamOutput) SetFileName(name string) *FileStreamOutput {
	f.fileName = name
	return f
}

// SetContentType changes the content type
func (f *FileStreamOutput) SetContentType(contentType string) *FileStreamOutput {
	f.contentType = contentType
	return f
}

// SetHeader adds a custom header
func (f *FileStreamOutput) SetHeader(key, value string) *FileStreamOutput {
	f.headers[key] = value
	return f
}

// DeleteFileAfterSend marks the file for deletion after sending
// Note: Actual deletion should be handled by the response writer
func (f *FileStreamOutput) DeleteFileAfterSend() *FileStreamOutput {
	f.headers["X-Delete-After-Send"] = "true"
	return f
}

// detectMimeType detects MIME type from file path
func detectMimeType(path string) string {
	// Try to detect from extension first
	ext := filepath.Ext(path)
	if mimeType := mime.TypeByExtension(ext); mimeType != "" {
		return mimeType
	}

	// Fallback: try to read file and detect
	file, err := os.Open(path)
	if err != nil {
		return "application/octet-stream"
	}
	defer file.Close()

	// Read first 512 bytes for detection
	buffer := make([]byte, 512)
	n, err := file.Read(buffer)
	if err != nil {
		return "application/octet-stream"
	}

	return http.DetectContentType(buffer[:n])
}

// detectMimeTypeFromFilename detects MIME type from filename
func detectMimeTypeFromFilename(filename string) string {
	ext := filepath.Ext(filename)
	if mimeType := mime.TypeByExtension(ext); mimeType != "" {
		return mimeType
	}
	return "application/octet-stream"
}

// Common MIME type constants for convenience
const (
	MimeTypeJSON        = "application/json"
	MimeTypeXML         = "application/xml"
	MimeTypeHTML        = "text/html"
	MimeTypePlain       = "text/plain"
	MimeTypeCSV         = "text/csv"
	MimeTypePDF         = "application/pdf"
	MimeTypeZIP         = "application/zip"
	MimeTypePNG         = "image/png"
	MimeTypeJPEG        = "image/jpeg"
	MimeTypeGIF         = "image/gif"
	MimeTypeSVG         = "image/svg+xml"
	MimeTypeWebP        = "image/webp"
	MimeTypeMP3         = "audio/mpeg"
	MimeTypeMP4         = "video/mp4"
	MimeTypeOctetStream = "application/octet-stream"
)
